### ISSUE TITLE
'WorkManagerSample' should use Hilt and App Startup library to initialize and provide WorkManager dependency

### ISSUE THREAD

**Issue by DivS-15** [android/architecture-components-samples#1059]
### Hilt should be used along with App Startup's Initializer interface to provide a WorkManager instance on first access.

>WorkManager should be initialized on-demand rather than when the app starts.
>
> WorkManager instance should be **injected** into the **ViewModel**.

#### Files that require refactoring so as to use **@ HiltWorker**
[workers.kt](https://github.com/DivS-15/architecture-components-samples/tree/main/WorkManagerSample/lib/src/main/java/com/example/background/workers)

#### Classes to add, so that we can use dependency injection for WorkManager instance:
1. object class **WorkManagerInitializerModule** (Hilt Module) in the **di** package (separate package for the WorkManagerSample app).

2. WorkManagerInitializerModule would implement **Initializer< WorkManager >** .

#### Tasks
- [ ] Write a **@ Provides** method by overriding **Initializer < WorkManager >'s** **create()** method inside a **Hilt Module**.
- [ ] consume the **WorkManager** dependency inside the **viewmodel's** constructor.
- [ ] Refactor the **worker classes** to use **@HiltWorker**.
- [ ] All relevant classes to use appropriate Hilt annotations.
